CREATE TABLE squad_finder_profiles (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    profile_name TEXT NOT NULL,
    platform TEXT NOT NULL,
    game TEXT NOT NULL,
    region TEXT NOT NULL
);