CREATE TABLE squad_finder_users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_name TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL
);

ALTER TABLE squad_finder_profiles
    ADD COLUMN
        user_id INTEGER REFERENCES squad_finder_users(id)
        ON DELETE SET NULL;