CREATE TABLE squad_finder_favorites (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    profile_name TEXT NOT NULL UNIQUE
);

ALTER TABLE squad_finder_users
    ADD COLUMN
        favorite_id INTEGER REFERENCES squad_finder_favorites(id)
        ON DELETE SET NULL;